services:
  db:
    image: postgis/postgis:16-3.4
    container_name: openland_db
    restart: always
    environment:
      POSTGRES_USER: openland_user
      POSTGRES_PASSWORD: openland_password
      POSTGRES_DB: openland_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
